### ISSUE TITLE
Got 404 on static files load on DEV mode

### ISSUE THREAD

**Issue by okayhooni** [gadsme/charts#23]
![image](https://github.com/gadsme/charts/assets/81631424/db8f0c65-997f-4a65-8e9d-1c4e08151fca)

Could I use your fancy chart with DEV mode playground..?

**Comment by okayhooni** [comment]
I god a solution..

Ingress path : / -> /*

```
spec:
  rules:
    - host: cube.beta.ds.woowa.in
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cube-api
                port:
                  name: http
```
