### ISSUE TITLE
cubestore error

### ISSUE THREAD

**Issue by saraswathirs** [gadsme/charts#35]
2023-10-07 09:06:54,513 ERROR [cubestore::cluster] <pid:1> Network error: Connection closed unexpectedly. Please check your worker and meta connection environment variables.
2023-10-07 09:07:46,733 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-07 09:07:47,433 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-07 09:14:02,944 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-07 09:17:18,187 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-10 11:10:43,378 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)
2023-10-10 11:11:07,793 ERROR [cubestore::http] <pid:1> Websocket error: Protocol(ResetWithoutClosingHandshake)

i am getting this error continuously, can some help me to fix this

**Comment by jlloyd-widen** [comment]
I'm getting this exact same behavior too.

I wonder if this has much to do with devMode problems mentioned in other issues? 🤷

**Comment by jlloyd-widen** [comment]
This appears to be from not allocating enough resources to the appropriate pods. See [this discussion](https://github.com/cube-js/cube/issues/8669) for more details. I updated the `values.yaml` with the config below and these errors went away:

```yaml
cube:
  extraEnvVars:
    - name: NODE_OPTIONS
      value: "--max-old-space-size=6144"

  api:
    apiCount: 2
    resources:
      requests:
        cpu: "2"
        memory: "3Gi"
      limits:
        cpu: "2"
        memory: "3Gi"

  worker:
    resources:
      requests:
        cpu: "2"
        memory: "6Gi"
      limits:
        cpu: "2"
        memory: "6Gi"

cubestore:
  router:
    resources:
      requests:
        cpu: "4"
        memory: "6Gi"
      limits:
        cpu: "4"
        memory: "6Gi"

  workers:
    workersCount: 2
    resources:
      requests:
        cpu: "4"
        memory: "8Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
```
