### ISSUE TITLE
Working Example of Enabling the SQL API: CUBEJS_PG_SQL_PORT

### ISSUE THREAD

**Issue by jlloyd-widen** [gadsme/charts#48]
This chart has some configuration around enabling the SQL API but when I enable it all my attempts to connect to it with a JDBC client timeout. Being new to K8s as I am, I'm not entirely sure how to enable this.

In addition to the config provide here, I added a path the ingress:
```
...
  rules:
    - host: {{ $.Values.cube.ingress.hostname }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: 4000
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: 15432
```
but this was clearly not enough. Could it have something to do with K8s not natively supporting anything other than http(s)?
